
name: deployment
on:
  push:
    branch: master
jobs:
  deploy:
    environment: ALI
    runs-on: ubuntu-latest
    env:
      DEPLOY_PATH: /data/apps/wenshubu
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      QILI: ${{ secrets.QILI }}
      QILI_CONTACT: ${{ secrets.QILI_CONTACT }}
      QILI_TOKEN: ${{ secrets.QILI_TOKEN }}
      QILI_APPID: 5b07b8571f6cab002e832d23

    steps:
      - run: sudo apt-get install -y sshpass
      - uses: actions/checkout@v3
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'
      - run: yarn

      - name: sync cloud code to ali cloud
        run: yarn sync --service $QILI --contact "$QILI_CONTACT" --token "$QILI_TOKEN"  --appId $QILI_APPID

      - name: build
        run: |
          yarn relay
          yarn build -p
      
      - name: zip and upload web pages
        run: | 
          rm dist/app.js
          cp node_modules/we-edit/font-service.js dist
          cp node_modules/we-edit/Arial dist/fonts
          node -p "require('./package.json').version" > dist/app.apk.version
          tar cvfz a.tgz dist
          export SSHPASS=${{ secrets.DEPLOY_PASS }}
          sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null a.tgz "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"
          sshpass -e ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $DEPLOY_USER@$DEPLOY_HOST "tar xvfz $DEPLOY_PATH/a.tgz -C $DEPLOY_PATH && rm $DEPLOY_PATH/a.tgz"
      
      - name: publish we-office-cli
        uses: JS-DevTools/npm-publish@v1
        with:
          package: packages/we-office-cli/package.json
          token: ${{ secrets.NPM_TOKEN }}